name: Procesar estado obra

on:
  push:
    paths:
      - 'data/estadoObra.xlsx'

permissions:
  contents: write

jobs:

  procesar_excel:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install pandas openpyxl

    - name: Ejecutar procesamiento del Excel
      run: python scripts/procesar_estado_obra.py

    - name: Commit y push del archivo generado
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/estadoObra_filtrado.csv
        git commit -m "Actualización automática archivo filtrado" || echo "No hay cambios para commit"
        git push
