name: Procesar estado obra

on:
  push:
    paths:
      - 'data/estadoObra.xlsx'

jobs:

  procesar_excel:

    runs-on: ubuntu-latest

    steps:

    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install pandas openpyxl

    - name: Ejecutar procesamiento
      run: python scripts/procesar_estado_obra.py

    - name: Commit archivo generado
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data/estadoObra_filtrado.csv
        git commit -m "Actualización automática archivo filtrado" || echo "Sin cambios"
        git push
